use schooldb;
INSERT INTO client (firstName, lastName, address, email) VALUES ("Maria", "Buda", "Lalelelor", "maria@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("Florin", "Bujor", "Alexandru Voda", "florin@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("Bianca", "Martin", "Crinilor", "bianca@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("David", "Popovici", "Revolutiei", "david@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("Crina", "Matei", "1 Decembrie", "crina@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("Xenia", "Vultur", "Pajistei", "vultur@gmail.com");
INSERT INTO client (firstName, lastName, address, email) VALUES ("Mircea", "Martin", "Montreal", "mircea@gmail.com");
INSERT INTO product (name, price, stock) VALUES ("laptop", 4999.99, 20);
INSERT INTO product (name, price, stock) VALUES ("telefon", 2499.49, 40);
INSERT INTO product (name, price, stock) VALUES ("husa", 140.37, 100);
INSERT INTO product (name, price, stock) VALUES ("aparat foto", 1799.20, 15);
INSERT INTO product (name, price, stock) VALUES ("smartTV", 3099.45, 25);
INSERT INTO orders (clientID, productID, quantity) VALUES (31, 12, 4);
INSERT INTO orders (clientID, productID, quantity) VALUES (32, 13, 2);
INSERT INTO orders (clientID, productID, quantity) VALUES (33, 14, 3);
INSERT INTO orders (clientID, productID, quantity) VALUES (34, 15, 4);
INSERT INTO orders (clientID, productID, quantity) VALUES (36, 16, 5);
INSERT INTO orders (clientID, productID, quantity) VALUES (36, 16, 2);
INSERT INTO orders (clientID, productID, quantity) VALUES (37, 13, 3);
INSERT INTO orders (clientID, productID, quantity) VALUES (32, 14, 1);
INSERT INTO orders (clientID, productID, quantity) VALUES (34, 12, 1);
